version: '3.8'
services:
  web:
    build: .
    container_name: recon
    restart: always
    ports:
    - "3123:8888"
    volumes:
      - "/srv/docker-data/DBS/recon_data:/root"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: '0'